export const ActionTypes = {
    GET_TOKEN: 'GET_TOKEN',
    GET_TOKEN_FAIL: 'GET_TOKEN_FAIL',
    GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

    LOGIN: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT: 'LOGOUT',

    GET_USER: 'GET_USER',
    GET_USER_FAIL: 'GET_USER_FAIL',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',

    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    
    UPDATE_FILES: 'UPDATE_FILES',
    UPDATE_FILES_SUCCESS: 'UPDATE_FILES_SUCCESS',
    UPDATE_FILES_FAIL: 'UPDATE_FILES_FAIL',


};

export const Errors = {
    UnknownError: "Unknown error!"
};